version: "3"

services:
  app:
    image: ${APP_NAME}:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: ${APP_NAME}
    volumes:
      - ./app:/var/app/
      - ./tests:/var/app/tests
      - ./vendor/autojs/src:/var/app/static/js/autojs
      - ./vendor/autostyle:/var/app/static/style/autostyle
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]
    ports:
      - "${APP_PORT}:5000"
  redis:
    image: redis/redis-stack:latest
    container_name: ${APP_NAME}_redis
    volumes:
      - ./tables/:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  redis_test:
    image: redis/redis-stack:latest
    container_name: ${APP_NAME}_redis_test
    volumes:
      - ./tables_test/:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
networks:
  default:
    name: ${APP_NAME}_net
