version: "3"

services:
  app:
    image: ${APP_NAME}:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: ${APP_NAME}
    networks:
      - auto_net
    volumes:
      - ./app:/var/app/
      - ./tests:/var/app/tests
      - ./vendor/autojs/src:/var/app/static/js/autojs
      - ./vendor/autostyle:/var/app/static/style/autostyle
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - worker
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: ${APP_NAME}_rabbitmq
    env_file: .env
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:15672"]
      test: ["CMD", "rabbitmqctl", "await_startup"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - auto_net
    stdin_open: true
    tty: true
  worker:
    build:
      context: .
      dockerfile: Dockerfile.tasks
    container_name: ${APP_NAME}_worker
    env_file: .env
    working_dir: /var/app
    volumes:
      - ./app:/var/app/
    networks:
      - auto_net
    command: celery -A tasks worker --loglevel DEBUG
    depends_on:
      rabbitmq:
        condition: service_healthy
  flower:
    image: mher/flower:latest
    container_name: ${APP_NAME}_flower
    env_file: .env
    environment:
      - CELERY_BROKER_URL=amqp://user:bitnami@rabbitmq
      - FLOWER_PORT=8888
    ports:
      - 8889:8888
    networks:
      - auto_net
    depends_on:
      - rabbitmq
networks:
  auto_net:
    name: auto_net
