version: "3"

services:
  redis:
    image: redis:latest
    container_name: ${APP_NAME}_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - auto_net
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  worker:
    image: pythonenv:latest
    build:
      context: .
      dockerfile: Dockerfile.tasks
    container_name: ${APP_NAME}_worker
    env_file: .env
    working_dir: /var/tasks
    volumes:
      - ./app/:/var/tasks/
    networks:
      - auto_net
    command: rq worker --name worker --url ${RQ_DEFAULT_CONNECTION}
    depends_on:
      redis:
        condition: service_healthy
  monitor:
    image: pythonenv:latest
    container_name: ${APP_NAME}_monitor
    env_file: .env
    ports:
      - 8889:${MONITOR_PORT}
    command: rq-dashboard --port ${MONITOR_PORT} --redis-url ${RQ_DEFAULT_CONNECTION}
    networks:
      - auto_net
    depends_on:
      - worker
  app:
    image: ${APP_NAME}:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: ${APP_NAME}
    networks:
      - auto_net
    volumes:
      - ./app:/var/app/
      - ./tests:/var/app/tests
      - ./vendor/autojs/src:/var/app/static/js/autojs
      - ./vendor/autostyle:/var/app/static/style/autostyle
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - worker
networks:
  auto_net:
    name: auto_net
